ALTER TABLE CATEGORIA ADD COLUMN descripcio VARCHAR(100) DEFAULT "nova categoria";
DESCRIBE CATEGORIA;

ALTER TABLE VALORACIONS ADD CONSTRAINT FK_id_client FOREIGN KEY (id_client) REFERENCES CLIENTS(id) ON DELETE CASCADE;
DESCRIBE VALORACIONS;
