CREATE TABLE PROVEIDORS(
id INTEGER UNSIGNED PRIMARY KEY,
nom VARCHAR(20),
correu VARCHAR(50),
telefon CHAR(9)
);

CREATE TABLE CATEGORIA(
id INTEGER UNSIGNED PRIMARY KEY,
nom VARCHAR(20)
);

CREATE TABLE PRODUCTE (
id INTEGER UNSIGNED PRIMARY KEY,
nom VARCHAR(20),
descripcio VARCHAR(100),
estoc INTEGER UNSIGNED,
id_proveidor INTEGER UNSIGNED, 
FOREIGN KEY (id_proveidor) REFERENCES PROVEIDORS(id)
);

CREATE TABLE CLIENTS(
id INTEGER UNSIGNED PRIMARY KEY,
nom VARCHAR(20),
cognom VARCHAR(20),
adreca VARCHAR(100),
correu VARCHAR(50)
);

CREATE TABLE DESCOMPTE(
id INTEGER UNSIGNED PRIMARY KEY,
percentatge INTEGER UNSIGNED,
data_inici DATE,
data_final DATE
);

CREATE TABLE COMANDES(
id INTEGER UNSIGNED PRIMARY KEY,
data DATE,
import_total DECIMAL (8,2),
estat ENUM ('en preparacio', 'entregada', 'cancelada'),
id_client INTEGER UNSIGNED,
FOREIGN KEY (id_client) REFERENCES CLIENTS(id) ON DELETE CASCADE
);

CREATE TABLE PRODUCTE_CATEGORIA(
id_producte INTEGER UNSIGNED,
id_categoria INTEGER UNSIGNED,
FOREIGN KEY (id_producte) REFERENCES PRODUCTE(id),
FOREIGN KEY (id_categoria) REFERENCES CATEGORIA(id)
);

CREATE TABLE PRODUCTE_DESCOMPTE(
id_producte INTEGER UNSIGNED,
id_descompte INTEGER UNSIGNED,
FOREIGN KEY (id_producte) REFERENCES PRODUCTE(id),
FOREIGN KEY (id_descompte) REFERENCES DESCOMPTE(id)
);

CREATE TABLE COMANDA_PRODUCTE(
quantitat INTEGER UNSIGNED,
id_comanda INTEGER UNSIGNED,
id_producte INTEGER UNSIGNED,
FOREIGN KEY (id_comanda) REFERENCES COMANDES(id),
FOREIGN KEY (id_producte) REFERENCES PRODUCTE(id)
);

CREATE TABLE VALORACIONS(
id_producte INTEGER UNSIGNED,
id_client INTEGER UNSIGNED,
puntuacio ENUM('1','2','3','4','5'),
comentari VARCHAR (100),
data DATE,
FOREIGN KEY (id_producte) REFERENCES PRODUCTE(id),
FOREIGN KEY (id_client) REFERENCES CLIENTS(id)
);

DESCRIBE PROVEIDORS;
DESCRIBE PRODUCTE;
DESCRIBE CLIENTS;
DESCRIBE COMANDES;
DESCRIBE PRODUCTE_CATEGORIA;
DESCRIBE PRODUCTE_DESCOMPTE;
DESCRIBE COMANDA_PRODUCTE;
DESCRIBE VALORACIONS;
