UPDATE PRODUCTE SET estoc = estoc + 50 WHERE estoc < 5;
SELECT * FROM PRODUCTE;

DELETE CLIENTS FROM CLIENTS LEFT JOIN COMANDES ON COMANDES.id_client = CLIENTS.id 
 WHERE COMANDES.id_client IS NULL;
SELECT * FROM CLIENTS;
